forge 'https://forgeapi.puppetlabs.com'

mod 'stahnma/epel'
mod 'puppetlabs/stdlib'
mod 'crayfishx/firewalld'

mod 'ebrc/ebrc_yum_repo',
  :git => 'git@github.com:EuPathDB/puppet-ebrc_yum_repo.git'

mod 'local/profiles',
  :path => './src/profiles'
  :latest
